### ISSUE TITLE
Run long video

### ISSUE THREAD

**Issue by shuyansy** [rese1f/MovieChat#53]
Thanks for your work. I want to test my long video and set the middle_video to 0. However, i met this error. Could you help me to provide some solutions? Thanks so much!

![截屏2024-04-26 下午9 24 11](https://github.com/rese1f/MovieChat/assets/50947689/6ec25d16-f8ed-4eab-8269-b0c11d688721)

**Comment by Espere-1119-Song** [comment]
I think I have fixed the bug before. Can u tell me which code u use? The error often occurs when u didn't initialize the long-term memory when update a new long video.

**Comment by shuyansy** [comment]
Hi, I just run the main branch. Moreover, i found "# middle_video = middle_video == 1" In line 368 in inference.py, So I delete it Do you have any ideas. Thanks so much for your reply!

**Comment by Espere-1119-Song** [comment]
![image](https://github.com/rese1f/MovieChat/assets/77435739/0e2f2978-f253-448d-afaf-4ea410b0ac85)
I think [line 368](https://github.com/rese1f/MovieChat/blob/main/inference.py) is not commented out.

**Comment by shuyansy** [comment]
Thanks so much！ The code can run normally. However, I want to read more frames so I  adjust " N_SAMPLES = 128", when I use larger number, the error still occurs. Do you have any ideas? Thanks for your time and response!

**Comment by Espere-1119-Song** [comment]
I think you need to check the actual length of positional embedding.

**Comment by shuyansy** [comment]
Thanks for the response. I expand "n_position = 16" to" n_position = 32" so it can support more frames. However I found the max value is 32 due to the size of the pretrained model. Thus, the max frame to model is about 500. Is my understanding right?

**Comment by Espere-1119-Song** [comment]
I think you can explore it by checking the length of long-term memory :). The max frame read by the model is len(short-term memory) * len(long-term memory) / 2

**Comment by shuyansy** [comment]
Thanks for reminder! The last question I want to check is whether my hyperparameter setting is right: cur_sec=1 cur_min=1  If I want to read the whole long video.
